### ISSUE TITLE
TypeError: "can't dump hash with default proc"

### ISSUE THREAD

**Issue by jstejada** [dblock/mongoid-cached-json#16]
I'm getting this error when calling as_json on my model, triggered on this line: 

https://github.com/dblock/mongoid-cached-json/blob/master/lib/mongoid-cached-json/cached_json.rb#L179

@dblock Do you have any ideas what the issue might be?

Thanks!

**Comment by dblock** [comment]
Looks like a hash with a default value cannot be serialized.

**Comment by jstejada** [comment]
That was the case, the hard part was figuring out why. I'm using sinatra and buildinga model from the the data in the params hash. My model has some hash fields which it assigns directly from the params hash.

As it turns out, sinatra builds the params hash with a default proc: https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L1060

This is why it was causing this error when I tried to serialize the model. Hope this helps someone else.
